name: Tweet art

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0/6 * * *" # Runs at every 6 hour from 0 through 23 UTC

jobs:
  tweet:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/cqhung1412/twitter-art-bot:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tweet
        run: npm start
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
#   notify:
#     runs-on: ubuntu-latest
#     if: always()
#     needs: tweet
#     steps:
#       - name: Send a Notification
#         uses: thechetantalwar/teams-notify@v2
#         with:
#           teams_webhook_url: ${{ secrets.TEAMS_HOOK }}
#           message: "Github Actions tweet art #${{ github.run_number }} completed for ${{ github.repository }} and the outcome is  ${{ needs.tweet.result }}."
